### ISSUE TITLE
Your timetable

### ISSUE THREAD

**Issue by ohnx** [ohnx/school#1]
@mebsim I'll fetch your timetable for you too, if you'd like.

**Comment by mebsim** [comment]
It's fine, I just was annoyed with the overcomplexity of your word/excel html page.

**Comment by mebsim** [comment]
The code (from excel) over complicates the font.

**Comment by ohnx** [comment]
I copied the table from excel into word, then I saved the page as an HTML file.

I don't dare look at the code generated.

**Comment by ohnx** [comment]
I copied the table from excel into word, then I saved the page as an HTML
file.

I don't dare look at the code generated.

Mason

**Comment by mebsim** [comment]
I know so I tried to fix it

**Comment by mebsim** [comment]
It looks similar except for a few things

**Comment by mebsim** [comment]
Why is there no README

**Comment by mebsim** [comment]
What do you mean by "fetch your timetable". I'm just confused by the idea of fetching something that only exists as a concept that is followed by a small number of people.

**Comment by ohnx** [comment]
lol no, i mean like i can get your timetable and format it in a similar way

**Comment by mebsim** [comment]
Does not matter, the year is done. Well nearly.
